#!/usr/bin/env python3
"""
@author: Ihab S. Mohamed, Vehicle Autonomy and Intelligence Lab - Indiana University, Bloomington, USA
"""
"""
@brief: The main ROS node for performing autonomous navigation of a differential wheeled robot (e.g., ClearPath Jackal robot)
based on MPPI and log-MPPI, assuming that the map (i.e., 2d_costmap) is genereted online using the onboard sensor.
"""
import datetime
import os
import sys
import time
import numpy as np
import cvxpy as cp
import signal
import rospy
import threading
import actionlib
# Import MPPI, Jackal Math. models, and utils
import utils as uls
from obstacle import Obstacle
from jackal import Jackal
from mppi_cbf import MPPI_Controller
from mppi_cbf_soft import MPPI_Controller_Soft

# ROS messages
# 导入 ROS 消息类型，涵盖了位置、目标、速度和标记等消息类型，便于机器人位置和地图的处理。
from geometry_msgs.msg import Point, PoseStamped, Twist
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
from nav_msgs.msg import OccupancyGrid, Odometry, Path
from std_msgs.msg import Bool
from std_msgs.msg import Float32MultiArray
from std_srvs.srv import Empty
from tf.transformations import euler_from_quaternion
from visualization_msgs.msg import Marker


# 定义 mppiControllerNode 类，用于管理 MPPI 控制节点的 ROS 相关功能，包括订阅和发布。
class mppiControllerNode():

    def __init__(self):

        # 获取控制频率（samplingRate 参数），设置循环速率控制器。
        self.hz = np.array(10.0)

        # To print out the current state and the optimal control generated by the controller
        # 获取 print_out 参数，用于确定是否打印出当前状态和控制器生成的最佳控制输入。
        self.print_out = False

        # 获取 trace_type 参数，用于确定跟踪方式。
			# 0：表示使用目标点跟踪。
			# 1：表示使用全局规划轨迹跟踪。-->        
        self.trace_type = 0
        self.start_time = 0 # 控制器启动时间
        self.firstrun_time = 0 # 首次运动抵达目标的时间
        self.firstrun = False
        self.run_time = 0
        self.ob_states_num = 7

        # 获取 without_heading 参数，控制是否在导航中忽略机器人方向信息。如果忽略，则输出相应日志提示。
        self.without_heading = True
        if self.without_heading:
            print(
                "Headless navigation task is being performed, ENJOY ;-)")
        else:
            print(
                "The navigation task is being performed taken into account the robot heading, ENJOY ;-)"
            )

        """ ROS publishers and subscribers """

        # state_dim：从参数服务器获取机器人状态的维度，作为一个数组存储。
        # control_dim：从参数服务器获取控制输入的维度。
        self.state_dim = 5
        self.control_dim = 2

        # state：用于保存机器人的当前状态，以零初始化。
        # targets：储存目标状态，以零初始化。
        self.state = np.zeros(self.state_dim, dtype=np.float32)
        self.targets = np.zeros(self.state_dim, dtype=np.float32)
        self.desired_pose = np.array([10.0, 0.0, 0.0, 0.0, 0.0])
        self.distanceToGoal = 1000000
        # 从参数服务器中获取机器人到达目标位置的最小距离阈值，确保机器人不会无限接近目标。
        self.minimumDistance = np.array(0.5)
        

        # Load MPPI controller parameters
        print("MPPI parameters are loaded..... Enjoy :-)")
        self.time_horizon = np.array(3) # time_horizon：从参数服务器获取时间范围，定义控制预测的未来时间长度。
        self.N = int(self.time_horizon*self.hz) # 步数


        self.exploration_variance = np.array(1200.0) # exploration_variance：控制随机轨迹探索的方差大小，用于增加轨迹多样性。
        self.num_trajectories = 2496 # num_trajectories：每次预测的轨迹数量。
        self.draw_num_traj = 50 # num_trajectories：每次预测的轨迹数量。
        self.weights = np.array([2.5, 2.5, 2, 0 ,0]) # weights：加载状态成本的权重，并扩展为与状态维度相匹配的数组。
        self.weights = self.weights * np.ones(self.state_dim, dtype=np.float32)

        """ 
            cbf 的 type：  0 欧式距离
            #             1 cos_超前
            #             2 pj超前
            #             3 dc
            #             4 扩展椭圆
        """
        self.cbf_type = 1
        """ 
            Get the type of the distribution that will be used for updating the control inputs
            self.dist_type = 0, for Normal
            self.dist_type = 1, for Norma and logNormal
            self.dist_type = 2, for ODAI
        """
        self.dist_type = 2 # 选择更新控制输入时使用的分布类型，0 表示正态分布，1 表示正态与对数正态结合。
        if self.dist_type == 0:
            self.std_n = np.array([0.2, 0.2]) # 控制噪声的标准差。
            #self.std_n = np.array([1.0, 1.0]) # 控制噪声的标准差。
            # self.std_n = np.array([0.052, 0.066]) # 控制噪声的标准差。
            self.lambda_ = 0.572 # MPPI控制器中的惩罚系数，影响控制成本
            self.beta_1 = 0.6 #轨迹 N-i退火系数 0.5为适当 i-(N,0)
            self.beta_2 = 0.6 #动作 T-t退火系数 0.5为适当 t-(0,T)
            self.beta_3 = 0.4 #障碍 D-d扩散系数 
        elif self.dist_type == 1:
            self.std_n = np.array([0.052, 0.057]) # 控制噪声的标准差。
            self.lambda_ = 0.169 # MPPI控制器中的惩罚系数，影响控制成本
            self.beta_1 = 0.6 #轨迹 N-i退火系数 0.5为适当 i-(N,0)
            self.beta_2 = 0.6 #动作 T-t退火系数 0.5为适当 t-(0,T)
            self.beta_3 = 0.4 #障碍 D-d扩散系数            
        elif self.dist_type == 2:
            self.std_n = np.array([0.0, 0.0]) # 控制噪声的标准差。
            self.beta_1 = 0.5 #轨迹 N-i退火系数 0.5为适当 i-(N,0)
            self.beta_2 = 0.8 #动作 T-t退火系数 0.5为适当 t-(0,T)
            self.beta_3 = 0.5 #障碍 D-d扩散系数 
            self.lambda_ = 0.236 # MPPI控制器中的惩罚系数，影响控制成本

        self.std_n_sla = 0.1 # 松弛变量 控制噪声的标准差。 标量

        # 将控制成本权重与扰动标准差成反比。
        # 理由是，如果扰动较大（std_n 大），意味着探索范围较宽，控制增益可以较小，从而减少对扰动的敏感性。
        # 如果扰动较小（std_n 小），意味着探索范围较窄，需要较大的控制增益来平衡控制成本的影响。
        
        self.R = 1 * self.lambda_ / self.std_n # 控制增益，使用 lambda_ 和 std_n 计算。
        self.r_sla = 1 * self.lambda_ / self.std_n_sla # 标量
        
        # Set the mean and standard deviation of Log-Normal dist based on the corresponding Normal distribution.
        
        self.mu_LogN, self.std_LogN = uls.Normal2LogN(0, np.mean(self.std_n)) # 根据正态分布的参数转换成对数正态分布的均值和标准差。
        self.LogN_info = [self.dist_type, self.mu_LogN, self.std_LogN] # 用于 MPPI 的分布信息数组，包括分布类型、对数正态均值、对数正态标准差。

        # For MPPI
         # Sigma_du：根据 dist_type 设置控制输入的噪声方差。dist_type=0 时使用标准正态分布，否则使用对数正态分布。
        if self.dist_type == 0:
            self.Sigma_du = np.square(self.std_n)
        # For log-MPPI
        else:
            self.Sigma_du = uls.NLN(0, np.square(self.std_n), self.mu_LogN,
                                    np.square(self.std_LogN))[1] # 


        # Load the parameters of the Savitsky Galoy filter
        # SG_window 和 SG_PolyOrder：从参数服务器获取用于平滑控制输入的 SG 滤波器窗口大小和多项式阶数。
        self.SG_window = np.array(51)
        self.SG_PolyOrder = np.array(3)

        # Get the maximum allowable velocities of the robot
        # max_linear_velocity 和 max_angular_velocity：机器人允许的最大线速度和角速度，用于限制控制输出。
        self.max_linear_velocity = np.array(1.2)
        self.max_angular_velocity = np.array(1.5)
        self.r = np.array(0.6)
        self.safety_dist = np.array(0.3)
        self.dcbf_alpha = np.array(0.1) 
        self.dcbf_weight = np.array(1000000)
        self.slack_weight = np.array(100)         
        self.check_dist = np.array(6.0) 
            # 1.0 非线性软约束； 0.1线性软约束
        self.max_slack_vari = np.array(1) 

        self.atau = np.array(0.2) 
        self.ob_num_max = np.array(5)
        self.soft_cbf = False
        self.IF_static_obs = False

        ''' Create a new instance of "Jackal" class and assign this object to the local variable "self.robot" '''
        # 实例化 Obstacle 类，赋值给 self.ob，用于表示障碍物，并传入障碍物数据、松弛变量软约束。
        self.obstacle = Obstacle(1 / float(self.hz), # 时间步长，用于更新位置。
                                self.time_horizon,
                                self.hz,
                                self.slack_weight,
                                self.max_slack_vari, # 定义了松弛变量最大变化率
                                num_max=self.ob_num_max, # 松弛变量状态向量的最大维数
                                soft_cbf=self.soft_cbf) # 用于随机数生成。

        
        ''' Create a new instance of "Jackal" class and assign this object to the local variable "self.robot" '''
        # 实例化 Jackal 类，赋值给 self.robot，用于表示机器人模型，并传入机器人的状态维度、控制频率、最大速度和地图信息。
        self.robot = Jackal(self.state_dim, 1 / float(self.hz),
                            self.max_linear_velocity,
                            self.max_angular_velocity,
                            self.r,
                            self.safety_dist,
                            self.atau,
                            self.ob_states_num,
                            cbf_type=self.cbf_type,
                            dcbf_alpha=self.dcbf_alpha,
                            dcbf_weight=self.dcbf_weight)



        ''' Create a new instance of "MPPI_Controller" class and assign this object to the 
            local variable "self.jackal_controller" '''
        # jackal_controller：实例化 MPPI 控制器，使用机器人的运动学和状态成本模型。MPPI 控制器将在每次循环中生成一系列候选控制输入，并从中选择最优控制输入。
        if not self.soft_cbf:
            self.jackal_controller = MPPI_Controller(self.state_dim,
                                                    self.control_dim,
                                                    self.num_trajectories,
                                                    self.draw_num_traj,
                                                    self.time_horizon,
                                                    self.hz,
                                                    self.exploration_variance,
                                                    self.robot.cuda_kinematics(),
                                                    self.robot.cuda_state_cost(),
                                                    self.SG_window,
                                                    self.SG_PolyOrder,
                                                    self.LogN_info,
                                                    self.cbf_type,
                                                    check_dist = self.check_dist,
                                                    beta_1 = self.beta_1,
                                                    beta_2 = self.beta_2,
                                                    beta_3 = self.beta_3,
                                                    lambda_=self.lambda_,
                                                    atau = self.atau)
        else:
            self.jackal_controller = MPPI_Controller_Soft(self.state_dim,
                                                    self.control_dim,
                                                    self.num_trajectories,
                                                    self.draw_num_traj,
                                                    self.time_horizon,
                                                    self.hz,
                                                    self.exploration_variance,
                                                    self.robot.cuda_kinematics(),
                                                    self.robot.cuda_state_cost(),
                                                    self.obstacle.cuda_kinematics(),
                                                    self.obstacle.cuda_state_cost(),                                                    
                                                    self.SG_window,
                                                    self.SG_PolyOrder,
                                                    self.LogN_info,
                                                    check_dist =self.check_dist,
                                                    beta_1 = self.beta_1,
                                                    beta_2 = self.beta_2,
                                                    beta_3 = self.beta_3,
                                                    ob_num_max=self.ob_num_max,
                                                    lambda_=self.lambda_)
        
        # Costs Initialization
        # state_cost 和 control_cost 初始化为 0，用于跟踪状态成本和控制成本。
        # fail 标志用于标记是否发生故障（如路径不可行）。
        # 调用 reset_controls 方法重置控制器的内部控制变量。
        self.state_cost, self.control_cost, self.fail = 0, 0, False
        self.sla_state_cost = 0 # 松弛变量代价
        # self.jackal_controller.reset_controls()

        # Repositories for saving the results
        # state_history、desired_state_history 和 control_history：存储历史状态、目标状态和控制命令。
        # state_cost_history 和 control_cost_history：存储每次状态和控制成本值，用于调试或日志记录。
        # mppi_time_history：记录 MPPI 计算时间历史数据。
        self.state_history, self.desired_state_history, self.control_history = [], [], []
        self.optimal_U_history,  self.sample_U_history = [], [] # 每刻的最优控制序列， 以及每刻的采样序列（取50条轨迹）
        self.state_cost_history, self.control_cost_history, self.min_cost_history = [], [], []
        self.ob_state_history, self.ob_slack_history = [], []
        self.mppi_time_history = []
        self.Jackal_states = ([0.01, 0.01, 0.0, 0, 0])
        self.local_costmap = []
        self.costmap_updated_origin = []
        # Create folder for saving data of the running mission
        # results_folder：从参数服务器获取结果保存文件夹路径，如果路径有效，则创建带时间戳的文件夹用于存储任务运行数据。
        results_folder = './results/sim_results'
        if results_folder:
            self.results_rootpath = os.path.join(
                results_folder,
                datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S'))
            os.makedirs(self.results_rootpath)
        else:
            self.results_rootpath = None

    ''' __enter__ 是 Python 中上下文管理器协议的一部分，允许类使用 with 语句进入上下文。在 with 语句中实例化时会自动调用该方法。 
        返回 self，以便在 with 语句块中继续使用当前对象实例。 '''
    def __enter__(self):
        return self

    def exceed_ob(self, ob_):
        # 获取障碍物的圆心坐标和半径
        ob_vec = np.array([ob_[0], ob_[1]])  # 障碍物圆心
        r = ob_[2]  # 圆的半径
        
        # 获取机器人当前位置
        curr_vec = self.Jackal_states[:2]  # 当前机器人的位置

        dist_robot_obstacle =  np.linalg.norm(curr_vec - ob_vec) - r - self.r
        if (dist_robot_obstacle <= 0):
           print("------- robot_obstacle crush !!!-------")
           print(f"crush dist: {dist_robot_obstacle}")
        dist_robot_obstacle = max(dist_robot_obstacle, 1e-6)

        return dist_robot_obstacle <= self.check_dist
    
    def obs_cb(self):
        self.all_ob_cur = []
        self.ob = []
        self.ob_cur_state = []
        self.ob_id = []
        
        self.obstacle.virtual_data = self.obstacle.update_predict_state_virtual(self.obstacle.virtual_ob_state)
        data = np.copy(self.obstacle.virtual_data)
        # print(f"data:={data}")
        num_obs = int(len(data) / (7*self.N))
        for i in range(num_obs):
            self.all_ob_cur.append(np.array(data[7*(i*self.N) : 7*(i*self.N + 1)]))
            if self.exceed_ob(data[7*i*self.N : 7*i*self.N+7]):
                self.ob_id.append(i)
                self.ob_cur_state.append(np.array(data[7*(i*self.N) : 7*(i*self.N + 1)]))
                for j in range(self.N):
                    self.ob.append(np.array(data[7*(i*self.N + j) : 7*(i*self.N + j + 1)]))
            else:
                print(f"ob{i}大于检测范围")
        # x y a b theta dx dy 
        self.obstacle.all_cur_state = self.all_ob_cur
        self.obstacle.data = self.ob
        self.obstacle.cur_state = self.ob_cur_state
        self.obstacle.num = int(len(self.ob_id))
        self.obstacle.id_last = self.obstacle.id
        self.obstacle.id = self.ob_id

    """ @brief: Checking out whether the desired pose is reached or not
            check_goal_reached 方法用于检查机器人是否已经达到目标点。 """
    def check_goal_reached(self, state, target):
        """
        Check if the position and orientation are close enough to the target.
        If this is the case, set the current goal to succeeded.
        """
        # 发布移动命令
            # 创建一个布尔消息cmd_move，并根据当前状态与全局路径最后一个点的距离决定是否发布移动命令。
        cmd_move = Bool()
        cmd_move.data = True
        # position_tolerance 和 orientation_tolerance 分别表示位置和方向容忍度。
        position_tolerance = self.minimumDistance - 0.1
        orientation_tolerance = 0.15

        # 计算 distanceToGoal，即当前状态与目标位置的距离。
        distanceToGoal = np.sqrt(
            np.square(target[1] - state[1]) + np.square(target[0] - state[0]))
        sys.stdout.write("distanceToGoal: %.3f\n" % distanceToGoal)
        # 若 distanceToGoal 小于位置容忍度，且角度误差小于方向容忍度，则调用 set_succeeded() 标记目标为已成功到达。

        if distanceToGoal < position_tolerance:
            # self._as.set_succeeded()
            sys.stdout.write("Reached Goal!!!!!!!!!----!-----!")
            cmd_move.data = False
            if not self.firstrun:
                self.firstrun = True
                self.firstrun_time = time.time() - self.start_time
                sys.stdout.write("firstrun_time: %.3f\n" % self.firstrun_time)
        print(cmd_move.data)
        return cmd_move.data
            
    """ @brief: Handling the robot's heading angle, based on each quarter, for performing a heading navigation 
            headingAngle 方法用于计算到目标的最优朝向。"""
    def headingAngle(self, current_state, desired_state):
        # delta_x 和 delta_y 分别为 x 和 y 坐标上的偏差，通过 arctan2 计算最优航向 desired_heading。
        delta_x = desired_state[0] - current_state[0]
        delta_y = desired_state[1] - current_state[1]
        desired_heading = np.arctan2(delta_y, delta_x)
        # 根据 current_state[2] 和 desired_heading 的差异判断当前朝向，考虑到不同象限的角度范围。
        # 调整 desired_heading 以确保其在合理范围内，并返回 desired_heading 和对应的 case（用于调试或控制）。
        if ((desired_heading - current_state[2]) <
            (-np.pi / 2.0)) and ((desired_heading - current_state[2]) >
                                 (-3.0 * np.pi / 2.0)):
            desired_heading = desired_heading - np.pi
            case = 1
        elif (((desired_heading - current_state[2]) > (np.pi / 2))
              and ((desired_heading - current_state[2]) <
                   (3.0 * np.pi / 2.0))):
            desired_heading = desired_heading + np.pi
            case = 2
        elif ((desired_heading - current_state[2]) < (-3.0 * np.pi / 2.0)):
            desired_heading = desired_heading + 2 * np.pi
            case = 3
        elif ((desired_heading - current_state[2]) > (3.0 * np.pi / 2.0)):
            desired_heading = desired_heading - 2 * np.pi
            case = 4
        else:
            desired_heading = desired_heading
            case = 5
        return desired_heading, case

    """ @brief: The primary function for running the MPPI algorithm 
            run_mppi 是主控制循环，通过 MPPI 算法计算最优路径。"""
    def run_mppi(self):
            # 若里程计数据有效，则设置初始位置 init_pose。
        if self.Jackal_states != None:
            print("The MPPI controller got first odometry message")
            self.init_pose = self.Jackal_states
            self.targets = np.copy(self.desired_pose)
        self.start_time = time.time()
        while self.check_goal_reached(self.Jackal_states, self.targets):
            """ Update the obstacle map based on the costmap acquired by the sensor """

                # 读取当前状态和目标位置。
            self.state = np.copy(self.Jackal_states)
            self.targets = np.copy(self.desired_pose)

            print(f"self.state:= {self.state}")
            print(f"self.targets:= {self.targets}")

                # 读取虚拟障碍的信息
            self.obs_cb()

                # 计算当前状态与目标位置之间的距离。
            self.distanceToGoal = np.sqrt(
                np.square(self.targets[1] - self.state[1]) +
                np.square(self.targets[0] - self.state[0]))
            
                # 如果无需朝向控制（without_heading），则直接使用当前 yaw 角度。
            if self.without_heading:
                if self.distanceToGoal > self.minimumDistance:
                    self.targets[2] = self.state[2]
                else:
                    self.targets[2] = self.desired_pose[2]
            else:
                # 若需控制朝向，则调用 headingAngle 方法设置 yaw，使机器人始终面向目标。
                desired_heading, case = self.headingAngle(
                    self.state, self.targets)
                if self.distanceToGoal > self.minimumDistance:
                    self.targets[2] = desired_heading
                else:
                    self.targets[2] = self.desired_pose[2]
                # Increase the weight of the 3rd state (yaw) so that the robot heads towards the goal ASAP
                self.weights[2] = 60.0


            # 加入 VO 引导采样






            # 开始计时并调用 compute_control 方法计算最优控制输入 u，记录执行时间 t_mppi。
            start = time.time()
            #################开始计时并调用 compute_control 方法计算最优控制输入 u，记录执行时间 t_mppi #############
            if not self.soft_cbf:
                u, optimal_U, sample_U, normalizer, min_cost = self.jackal_controller.compute_control(
                    self.state,
                    [self.std_n, self.R, self.weights, self.targets, self.obstacle.data, self.obstacle.num])
                
            else:
                # print(f"self.U := {self.jackal_controller.U}") 
                u, optimal_U, sample_U, ob_u, normalizer, min_cost = self.jackal_controller.compute_control(
                    self.state,
                    [self.std_n, self.R, self.weights, self.targets], 
                        [self.obstacle.data, self.obstacle.num, self.obstacle.id, 
                            self.r_sla, self.std_n_sla, self.obstacle.U, self.obstacle.state_sla])    
                

            if (u[0] > self.max_linear_velocity):
                u[0] = self.max_linear_velocity
            
            if (u[0] < - self.max_linear_velocity):
                u[0] = - self.max_linear_velocity
            

            if (u[1] > self.max_angular_velocity):
                u[1] = self.max_angular_velocity
            
            if (u[1] < - self.max_angular_velocity):
                u[1] = - self.max_angular_velocity
            

            # The excution time of MPPI
            t_mppi = time.time() - start
            if self.soft_cbf:
                # 更新障碍物松弛变量状态
                self.obstacle.state_sla = self.obstacle.update_state(self.obstacle.state_sla, ob_u)           
                self.sla_state_cost = self.obstacle.cost(self.obstacle.state_sla,
                                        [self.obstacle.weights, self.obstacle.target_sla])
                self.ob_slack_history.append(np.copy(self.obstacle.state_sla))   
                print(f"state_sla:{self.obstacle.state_sla}")
                print(f"self.sla_state_cost:{self.sla_state_cost}")                
                    
            
            # Record the costs
            # 计算状态代价和控制代价，将结果保存至 state_cost 和 control_cost
            costs = self.robot.cost(self.state, u,
                                    [self.weights, self.targets, self.R])
            self.state_cost = costs[0]
            self.control_cost = costs[1]


            # 计算总成本
            total_cost = self.state_cost + self.control_cost + self.sla_state_cost
            # print(f"self.state_cost:{self.state_cost}")
            # print(f"min_cost:{min_cost}")

            # 打印总成本
            # print("Total Cost:", total_cost)

            # Record and update the state, and the mppi excution time
            # 将当前控制输入 u、状态、代价和执行时间等历史信息存储以供分析和调试。
            
            self.control_history.append(u)
            self.state_history.append(np.copy(self.state))

            self.optimal_U_history.append(np.copy(optimal_U))
            sample_U = sample_U.reshape(self.draw_num_traj, self.N, self.control_dim)
            self.sample_U_history.append(np.copy(sample_U))

            self.ob_state_history.append(np.copy(self.obstacle.all_cur_state))

            self.desired_state_history.append(np.copy(self.targets))
            self.state_cost_history.append(self.state_cost)
            self.min_cost_history.append(min_cost)
            self.control_cost_history.append(self.control_cost)
            if t_mppi*1000 > 10:
                print(f"t_mppi:{t_mppi*1000}")
                t_mppi = 0.0
            self.mppi_time_history.append(t_mppi* 1000) # 转毫秒
            self.run_time = len(self.mppi_time_history) * 0.1
            if(self.run_time>50):
                break


            # 如果 print_out 为真，则输出当前状态、执行时间和控制输入，以便调试。
            if self.print_out:
                sys.stdout.write(
                    "Current States: (%f, %f, %f), t_mppi: %f \n" %
                    (self.state[0], self.state[1],
                        self.state[2] * 180 / np.pi, t_mppi))
                sys.stdout.write("U: (%f, %f) \n" % (u[0], u[1]))
                print(
                    "------------------------------------------------------"
                )
                sys.stdout.flush()
            if np.isnan(np.sum(self.state)):
                print("Breaking MPPI due to numerical errors")
                self.fail = True
                break
            
            # 更新 機器人狀態
            self.Jackal_states = self.robot.update_state(self.state, u)
            # print(f"Jackal_states:{self.Jackal_states}")
            # 更新 机器人状态
            self.obstacle.update_cur_state_virtual(self.obstacle.virtual_ob_state)
            # print(f"obstacle_states:{self.obstacle.virtual_ob_state}")

    """ @brief: Plotting the states, corresponding optimal control action,and instantaneous running cost """
    def dataPlotting(self):
        obs_num = int(len(self.ob_state_history[0]))
        uls.statePlotting(self.state_history, self.results_rootpath) # dataPlotting 方法用于绘制机器人的状态、控制输入和运行代价随时间的变化曲线，帮助分析控制效果。
        uls.controlPlotting(self.control_history, self.results_rootpath) # uls.statePlotting(self.state_history, self.results_rootpath) 调用外部库函数 statePlotting，绘制 state_history 中的状态数据（位置和朝向）并保存到 results_rootpath 路径。
        uls.costPlotting(self.state_cost_history, self.control_cost_history,
                         self.min_cost_history, self.mppi_time_history,
                         self.results_rootpath) # uls.costPlotting 方法绘制不同代价（状态代价、控制代价、最小代价）以及 MPPI 执行时间的变化情况。
        if self.soft_cbf:
            uls.slackPlotting(self.ob_slack_history, obs_num, self.results_rootpath)
        uls.pathPlotting(obs_num, self.r, self.targets, self.results_rootpath)
        uls.plot_cbf(1 / float(self.hz), obs_num, self.r, self.safety_dist, self.results_rootpath,  self.IF_static_obs)
        uls.animate_simulation(1 / float(self.hz) , obs_num, self.safety_dist, self.r, self.atau, self.targets, 
                                self.results_rootpath, self.sample_U_history, optimal_us = self.optimal_U_history, cbf_type = self.cbf_type)
        
    ''' @brief: Retrieving the controllers' parameters, the costmap information, and summary of the performance'''
    def test_summary(self):
        if self.distanceToGoal > 0.5:
            self.local_minima = True
        else:
            self.local_minima = False
            # test_summary 方法生成控制器的性能摘要信息。
            # distanceToGoal > 0.5 表明机器人未能足够接近目标，设置 self.local_minima = True 表示可能陷入局部最小值。

        #self.map_info = 'cost-map'
        control_history = np.array(self.control_history) # 将 control_history 转换为 numpy 数组，以便方便地访问和处理控制数据。

        # 检查 control_history 是否有超过 max_linear_velocity 或 max_angular_velocity 的值，如果超出则设置 violate_ctrl_const 为 True，表示违反了速度约束。
        if max(control_history[:, 0]) > self.max_linear_velocity or max(
                control_history[:, 1]) > self.max_angular_velocity:
            self.violate_ctrl_const = True
        else:
            self.violate_ctrl_const = False

        # 将 state_history 中的 x 和 y 位置提取出来，并传递给 uls.pathLength(x, y) 计算机器人的行驶路径长度 pathLength。
        x, y = [s[0] for s in self.state_history
                ], [s[1] for s in self.state_history]
        self.pathLength = uls.pathLength(x, y)
        # Compute the avarage excution time of MPPI over all iterations
        # 计算 MPPI 在所有迭代中的平均执行时间 av_t_mppi。
            # 若 av_t_mppi 小于控制频率（1 / self.hz）的倒数，则设置 real_time_mppi 为 True，表示 MPPI 实时控制成功。
        self.av_t_mppi = np.mean(np.array(self.mppi_time_history)[20:])
        if self.av_t_mppi < 1 / float(self.hz):
            self.real_time_mppi = True
        else:
            self.real_time_mppi = False

        self.var_v =  uls.var_v(self.control_history)
        self.average_v =  uls.average_v(self.control_history)
        # self.var_v = 0
        # print(f"self.control_history:{self.control_history}")
        # 调用 uls.testSummaryMPPI 方法生成测试摘要，保存控制器的参数、性能指标等信息，包括初始状态 init_pose、目标 targets、控制器限制（最大线速度、角速度等）和代价权重 weights。
        
        obs_num = int(len(self.ob_state_history[0]))


        # save_results 将历史数据（状态、目标状态、代价和控制）保存在 results_rootpath 以供后续查看。
        uls.save_results(self.state_history, self.desired_state_history,
                         self.state_cost_history, self.min_cost_history,
                         self.control_history, self.mppi_time_history,
                         self.results_rootpath)

        uls.save_obs_results(obs_num, self.results_rootpath, self.ob_state_history, self.ob_slack_history)

        uls.save_time_results(self.results_rootpath, self.mppi_time_history)


        mindist = uls.cla_mindist(self.r, obs_num, self.results_rootpath)          

        uls.testSummaryMPPI(
            self.init_pose, self.targets, self.max_linear_velocity,
            self.max_angular_velocity, self.time_horizon,
            self.hz, self.weights, self.num_trajectories, self.R,
            self.Sigma_du, self.exploration_variance, self.lambda_,
            self.slack_weight,self.std_n_sla,self.atau,
            self.beta_1, self.beta_2, self.beta_3, self.check_dist,
            self.SG_window, self.SG_PolyOrder, self.dist_type, self.cbf_type, 
            self.local_minima, self.violate_ctrl_const, self.pathLength,self.var_v,self.average_v,mindist,
            self.av_t_mppi, self.real_time_mppi, self.firstrun_time, self.run_time, self.results_rootpath)



if __name__ == "__main__":
    # 主函数用于创建并运行 mppiControllerNode 实例，依次调用以下步骤：
    MPPI_Controller_Node = mppiControllerNode()
    MPPI_Controller_Node.run_mppi() # 运行主控制循环。
    MPPI_Controller_Node.test_summary()# 生成控制测试摘要，记录控制参数和性能信息。
    MPPI_Controller_Node.dataPlotting() # 将控制过程中的状态和代价数据进行可视化。
